### PR TITLE
Test merge #1

### PR DESCRIPTION
**Pull request by jlindgren90**

### CODE REVIEW

**Comment by Consolatis** [comment]
> This branch has no conflicts with the base branch.

And yet "Rebase and Merge" doesn't work?

Hm.. b3d19b945281b466258e0d908f19b08ccc7d968c also seems to contain much more than just conflict resolution.

**Comment by jlindgren90** [comment]
Yes, merge says it will work but selecting "rebase and merge" reports conflicts:
image
image

`git show` on the merge commit:
image

**Comment by Consolatis** [comment]
Strange. Guess we should figure this out first before starting with the "official" branch.

**Comment by jlindgren90** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-commits seems relevant.

> You aren't able to automatically rebase and merge on GitHub.com when:
> - The pull request has merge conflicts.
> - Rebasing the commits from the base branch into the head branch runs into conflicts.
> - Rebasing the commits is considered "unsafe," such as when a rebase is possible without merge conflicts but would produce a different result than a merge would.

`git rebase` does report a conflict in this case:
image

**Comment by jlindgren90** [comment]
I think it is just an issue with GitHub PRs not supporting this type of merge. If I were to push b3d19b945281b466258e0d908f19b08ccc7d968c (`test-merge`) directly to `test-merge-target` branch it would work fine, since `test-merge-target` is an ancestor of `test-merge` already.

**Comment by jlindgren90** [comment]
Note that "Merge pull request" (without rebase) would add a second merge commit, which seems unnecessary/undesirable. What we want is a "fast-forward merge" which is not an option in a GitHub PR.

**Comment by jlindgren90** [comment]
If GitHub used the magical/incomprehensible `git rebase --rebase-merges` rather than plain `git rebase` it would also work.

**Comment by Consolatis** [comment]
Hm.. so this basically means we can't use PRs at all for syncing from master then?

**Comment by jlindgren90** [comment]
> Hm.. so this basically means we can't use PRs at all for syncing from master then?

Yes, that's my conclusion at least. IMO it's not a big deal to allow directly syncing/merging (without a PR) since it is a development branch anyway.

**Comment by Consolatis** [comment]
I agree, getting notifications would still be great. But its not a deal breaker for me.

**Pull request closed without merging**
